"""Assembling the plate and its gazetteer.

A map is half the artefact. The other half is the index: the list at the back
that tells you the Tarkecrag range runs across the north-east, that its highest
point is 5,723 metres, and that the people who named it also named everything
within two hundred kilometres and nothing beyond.

This module turns a :class:`~silt.world.World` into files:

``<name>.svg``   the plate, self-contained, raster embedded
``<name>.png``   the ground raster on its own
``<name>.md``    the gazetteer, as prose and tables
``<name>.json``  every measurement, for anyone who wants to do their own thing
``<name>.html``  plate and gazetteer on one page, ready to open in a browser
"""

from __future__ import annotations

import json
import os
import re

from . import png as png_mod
from .climate import BIOMES
from .render import draw, raster
from .util import plural


def _slug(text: str) -> str:
    cleaned = re.sub(r"[^a-z0-9]+", "-", str(text).lower()).strip("-")
    return cleaned or "world"


def _bearing(world, x: float, y: float) -> str:
    return world.namer.compass_word(x, y)


def _cell_bearing(world, index: int) -> str:
    return _bearing(world, index % world.width, index // world.width)


# -- gazetteer ------------------------------------------------------------


def gazetteer(world) -> str:
    """The written half of the atlas, as Markdown."""
    features = world.features
    climate = world.climate
    lines = []
    add = lines.append

    lat_lo = climate.latitude(world.height_cells - 1)
    lat_hi = climate.latitude(0)
    lat_lo, lat_hi = min(lat_lo, lat_hi), max(lat_lo, lat_hi)

    add(f"# {world.title}")
    add("")
    add(f"*Seed `{world.seed}` · generated by Silt*")
    add("")

    shape_prose = {
        "continent": "a single landmass",
        "archipelago": "a scattering of islands",
        "peninsulas": "a ragged, deeply indented coast",
        "inland sea": "a ring of land around an enclosed sea",
    }.get(world.shape, world.shape)

    biomes = climate.biome_fractions(world.land_mask)
    leading = ", ".join(
        f"{BIOMES[key][0].lower()} ({share:.0%})" for key, share in biomes[:3]
    )
    peak = world.highest()

    add(
        f"{world.name} is {shape_prose} between {lat_lo:.0f}° and {lat_hi:.0f}° of "
        f"latitude, {world.width * world.cell_km:,.0f} km across. "
        f"Its {world.land_cell_count() * world.cell_km ** 2:,.0f} km² of land carry "
        f"{world.coast_km():,.0f} km of coastline. The prevailing wind comes from "
        f"the {climate.wind}, so rain falls on the {climate.wind}ward slopes and "
        f"the far side of every range lies in its shadow. The ground is mostly "
        f"{leading}. The highest point stands {world.metres(peak):,.0f} m above the "
        f"sea, in the {_cell_bearing(world, peak)} quarter."
    )
    add("")

    tongues = world.namer.languages
    if len(tongues) == 1:
        add("Every name on this sheet comes from a single tongue:")
    else:
        add(
            f"Names on this sheet come from {len(tongues)} tongues, each holding "
            f"the ground nearest its own centre:"
        )
    add("")
    for language in tongues:
        add(f"- **{language.name}** — {language.blurb}")
    add("")

    if features.regions:
        add("## Regions")
        add("")
        add("| Region | Predominant cover | Area |")
        add("|---|---|---|")
        for region in sorted(features.regions, key=lambda r: -r.area_km2):
            add(
                f"| {region.name} | {BIOMES[region.biome][0].lower()} "
                f"| {region.area_km2:,.0f} km² |"
            )
        add("")

    if features.rivers:
        add("## Rivers")
        add("")
        add("| River | Length | Order | Mouth |")
        add("|---|---|---|---|")
        for river in sorted(features.rivers, key=lambda r: -r.length_km):
            add(
                f"| {river.name} | {river.length_km:,.0f} km | {river.order} "
                f"| {_cell_bearing(world, river.mouth)} coast |"
            )
        add("")
        add(
            "*Order is the Strahler number: two streams of equal order meet to "
            "make one of the next order up. Nothing here was drawn — every "
            "watercourse is a line of cells that accumulated more than "
            f"{world.hydro.channel_area:,.0f} cells' worth of drainage.*"
        )
        add("")

    if features.ranges:
        add("## Highlands")
        add("")
        add("| Range | Highest point | Extent |")
        add("|---|---|---|")
        summit_by_index = {s.index: s for s in features.summits}
        for mountains in sorted(features.ranges, key=lambda r: -r.peak_m):
            summit = summit_by_index.get(mountains.peak)
            peak_name = f"{summit.name}, " if summit else ""
            add(
                f"| {mountains.name} | {peak_name}{mountains.peak_m:,.0f} m "
                f"| {mountains.area_km2:,.0f} km² |"
            )
        add("")

    if features.lakes:
        add("## Lakes")
        add("")
        for lake in sorted(features.lakes, key=lambda l: -l.area_km2):
            add(
                f"- **{lake.name}** — {lake.area_km2:,.0f} km², "
                f"{_bearing(world, *lake.centroid)} interior"
            )
        add("")

    if features.islands:
        add("## Islands")
        add("")
        for island in sorted(features.islands, key=lambda i: -i.area_km2):
            add(
                f"- **{island.name}** — {island.area_km2:,.0f} km², "
                f"off the {_bearing(world, *island.centroid)} shore"
            )
        add("")

    if features.waters or features.capes:
        add("## Waters and headlands")
        add("")
        for water in features.waters:
            where = _cell_bearing(world, water.index)
            if water.area_km2:
                add(f"- **{water.name}** ({water.kind}) — {water.area_km2:,.0f} km², {where}")
            else:
                add(f"- **{water.name}** ({water.kind}) — {where} coast")
        for cape in features.capes:
            add(f"- **{cape.name}** (cape) — {_cell_bearing(world, cape.index)} coast")
        add("")

    add("## How this sheet was made")
    add("")
    add(
        "Fractal noise raised a landmass and set two or three mountain belts "
        "along the zero-contours of a smooth field. Stream-power erosion then "
        f"ran for a number of steps, each one routing water over the whole grid "
        f"and cutting in proportion to how much passed and how steeply it fell. "
        f"The drainage network, the {len(features.rivers)} named "
        f"{plural(len(features.rivers), 'river')}, the lakes and the shape of "
        f"every valley are consequences of that, not decisions. Rain was swept "
        f"across the map from the {climate.wind} and dropped where the ground "
        f"rose. Biomes follow from the rain and the latitude. The names came "
        f"last, because what you call a place depends on what it turned out to be."
    )
    add("")
    add(f"Reproduce this world exactly with `silt {world.seed}`.")
    add("")
    return "\n".join(lines)


# -- html -----------------------------------------------------------------

_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<style>
  :root {{
    --paper: #f4efe2; --ink: #2f2c26; --soft: #6b6558; --rule: #d8cfba;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --paper: #14130f; --ink: #e8e2d3; --soft: #a49c8a; --rule: #34312a; }}
  }}
  * {{ box-sizing: border-box; }}
  body {{
    margin: 0; padding: 2.5rem 1.25rem 5rem; background: var(--paper);
    color: var(--ink); font: 16px/1.65 Georgia, 'Times New Roman', serif;
  }}
  main {{ max-width: 62rem; margin: 0 auto; }}
  figure {{ margin: 0 0 3rem; }}
  figure svg {{ width: 100%; height: auto; display: block; }}
  h1 {{ font-size: 2.1rem; letter-spacing: 0.01em; margin: 0 0 0.35rem; }}
  h2 {{
    font-size: 1.1rem; letter-spacing: 0.14em; text-transform: uppercase;
    margin: 2.6rem 0 0.9rem; padding-bottom: 0.4rem;
    border-bottom: 1px solid var(--rule); font-weight: normal;
  }}
  p, li {{ color: var(--ink); }}
  em, .lede {{ color: var(--soft); }}
  table {{ border-collapse: collapse; width: 100%; margin: 0 0 1rem; }}
  th, td {{
    text-align: left; padding: 0.4rem 0.6rem; border-bottom: 1px solid var(--rule);
    font-size: 0.94rem;
  }}
  th {{
    font-weight: normal; letter-spacing: 0.08em; text-transform: uppercase;
    font-size: 0.76rem; color: var(--soft);
  }}
  code {{ font-family: ui-monospace, 'Cascadia Code', Menlo, monospace; font-size: 0.86em; }}
  .wrap {{ overflow-x: auto; }}
</style>
</head>
<body>
<main>
<figure>
{svg}
</figure>
{body}
</main>
</body>
</html>
"""


def _markdown_to_html(markdown: str) -> str:
    """Enough Markdown for the gazetteer: headings, tables, lists, bold, italic."""
    html = []
    rows = []

    def flush_table():
        if not rows:
            return
        header, *body = rows
        if body and set(body[0].replace("|", "").strip()) <= set("-: "):
            body = body[1:]
        html.append('<div class="wrap"><table>')
        cells = [c.strip() for c in header.strip("|").split("|")]
        html.append("<tr>" + "".join(f"<th>{c}</th>" for c in cells) + "</tr>")
        for line in body:
            cells = [c.strip() for c in line.strip("|").split("|")]
            html.append("<tr>" + "".join(f"<td>{c}</td>" for c in cells) + "</tr>")
        html.append("</table></div>")
        rows.clear()

    def inline(text: str) -> str:
        text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
        text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
        text = re.sub(r"`(.+?)`", r"<code>\1</code>", text)
        return text

    in_list = False
    for line in markdown.splitlines():
        stripped = line.strip()
        if stripped.startswith("|"):
            if in_list:
                html.append("</ul>")
                in_list = False
            rows.append(stripped)
            continue
        flush_table()

        if not stripped:
            if in_list:
                html.append("</ul>")
                in_list = False
            continue
        if stripped.startswith("- "):
            if not in_list:
                html.append("<ul>")
                in_list = True
            html.append(f"<li>{inline(stripped[2:])}</li>")
            continue
        if in_list:
            html.append("</ul>")
            in_list = False
        if stripped.startswith("## "):
            html.append(f"<h2>{inline(stripped[3:])}</h2>")
        elif stripped.startswith("# "):
            html.append(f"<h1>{inline(stripped[2:])}</h1>")
        else:
            classes = ' class="lede"' if stripped.startswith("*") else ""
            html.append(f"<p{classes}>{inline(stripped)}</p>")
    if in_list:
        html.append("</ul>")
    flush_table()
    return "\n".join(html)


def atlas_html(world, svg: str, markdown: str) -> str:
    """One page: the plate, then the gazetteer under it."""
    # Drop the XML-level width/height so the plate scales with the page.
    inline_svg = re.sub(
        r'(<svg\b[^>]*?)\s+width="[\d.]+"\s+height="[\d.]+"', r"\1", svg, count=1
    )
    body = _markdown_to_html(markdown)
    # The <h1> already appears inside the gazetteer; keep the browser tab honest.
    return _HTML_TEMPLATE.format(
        title=world.title.replace("<", "&lt;"), svg=inline_svg, body=body
    )


# -- writing --------------------------------------------------------------

FORMATS = ("svg", "png", "md", "json", "html")


def render_atlas(
    world,
    directory: str = ".",
    scale: int = 4,
    formats=FORMATS,
    basename: str | None = None,
    **draw_options,
):
    """Write the requested formats; returns ``{format: path}``."""
    formats = tuple(formats)
    unknown = set(formats) - set(FORMATS)
    if unknown:
        raise ValueError(f"unknown format(s): {', '.join(sorted(unknown))}")

    os.makedirs(directory, exist_ok=True)
    stem = basename or _slug(f"{world.name}-{world.seed}")
    written = {}

    svg = None
    if {"svg", "html"} & set(formats):
        svg = draw(world, scale=scale, **draw_options)

    markdown = None
    if {"md", "html"} & set(formats):
        markdown = gazetteer(world)

    if "svg" in formats:
        path = os.path.join(directory, f"{stem}.svg")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(svg)
        written["svg"] = path

    if "png" in formats:
        path = os.path.join(directory, f"{stem}.png")
        rw, rh, pixels = raster(world, scale)
        png_mod.write(path, rw, rh, pixels)
        written["png"] = path

    if "md" in formats:
        path = os.path.join(directory, f"{stem}.md")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(markdown)
        written["md"] = path

    if "json" in formats:
        path = os.path.join(directory, f"{stem}.json")
        with open(path, "w", encoding="utf-8") as handle:
            json.dump(world.summary(), handle, indent=2)
            handle.write("\n")
        written["json"] = path

    if "html" in formats:
        path = os.path.join(directory, f"{stem}.html")
        with open(path, "w", encoding="utf-8") as handle:
            handle.write(atlas_html(world, svg, markdown))
        written["html"] = path

    return written
